version: "3.7"

services:
  app:
    image: testaustime-frontend
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - VITE_API_URL=https://api.testaustime.fi
    ports:
      - 3000:80
